# **Homework**: Data talks club data engineering zoomcamp Data loading workshop

Hello folks, let's practice what we learned - Loading data with the best practices of data engineering.

Here are the exercises we will do

# 1. Use a generator

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

**Answer the following questions:**

- **Question 1: What is the sum of the outputs of the generator for limit = 5?**
- **Question 2: What is the 13th number yielded**

I suggest practicing these questions without GPT as the purpose is to further your learning.

In [28]:
#Question 1
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)
value=0
for sqrt_value in generator:
    value=value+sqrt_value
print(value)

8.382332347441762

In [27]:
#Question 2
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 13
generator = square_root_generator(limit)
value_list=[]
for sqrt_value in generator:

    value_list.append(sqrt_value)
print(value_list[12])

3.605551275463989

# 2. Append a generator to a table with existing data


Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.
3. **After correctly appending the data, calculate the sum of all ages of people.**

In [30]:
#Question 3
import dlt

# define the connection to load to.
# We now use duckdb, but you can switch to Bigquery later
generators_pipeline = dlt.pipeline(destination='duckdb', dataset_name='people')


def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

for person in people_1():
    print(person)





def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}


for person in people_2():
    print(person)

info = generators_pipeline.run(people_1(),
										table_name="people_1",
										write_disposition="replace")

info = generators_pipeline.run(people_2(),
										table_name="people_1",
										write_disposition="append")
# show outcome

import duckdb

conn = duckdb.connect(f"{generators_pipeline.pipeline_name}.duckdb")

# let's see the tables
conn.sql(f"SET search_path = '{generators_pipeline.dataset_name}'")
print('Loaded tables: ')
display(conn.sql("show tables"))

# and the data

print("\n\n\n http_download table below:")

people = conn.sql("SELECT * FROM people_1").df()
age_sum=conn.sql("SELECT SUM(age) FROM people_1")
display(people,age_sum)

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}

2024-02-13 22:33:55,393|[WARNING              ]|266|133297725386752|dlt|reference.py|_verify_schema:357|A column record_hash in table people_1 in schema dlt_colab_kernel_launcher is incomplete. It was not bound to the data during normalizations stage and its data type is unknown. Did you add this column manually in code ie. as a merge key?
2024-02-13 22:33:55,989|[WARNING              ]|266|133297725386752|dlt|reference.py|_verify_schema:357|A column record_hash in table people_1 in schema dlt_colab_kernel_launcher is incomplete. It was not bound to the data during normalizations stage and its data type is unknown. Did you add this column manually in code ie. as a merge key?

Loaded tables:

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people_1            │
└─────────────────────┘

 http_download table below:

    id      name  age    city        _dlt_load_id         _dlt_id occupation
0    1  Person_1   26  City_A  1707863635.0159163  aRNM3qiYlyTsqQ       None
1    2  Person_2   27  City_A  1707863635.0159163  jRsxkQYUGtDpPQ       None
2    3  Person_3   28  City_A  1707863635.0159163  oV2e3wh1/CdsUg       None
3    4  Person_4   29  City_A  1707863635.0159163  VRNR2rI6EsPqbQ       None
4    5  Person_5   30  City_A  1707863635.0159163  8ILZm8biQEilfw       None
5    3  Person_3   33  City_B  1707863635.6062338  H+AuOBBLutvsQA      Job_3
6    4  Person_4   34  City_B  1707863635.6062338  /0lG2b80mSdLmQ      Job_4
7    5  Person_5   35  City_B  1707863635.6062338  RAHRtgOp7TZeXw      Job_5
8    6  Person_6   36  City_B  1707863635.6062338  BMrcXd24Z/uH/A      Job_6
9    7  Person_7   37  City_B  1707863635.6062338  RAJFgKkqJalRpQ      Job_7
10   8  Person_8   38  City_B  1707863635.6062338  PnGENTJ9UwyJ7A      Job_8

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      353 │
└──────────┘

In [31]:
info = generators_pipeline.run(people_1(),
										table_name="people_1",
										write_disposition="replace",
                               primary_key="ID")

info = generators_pipeline.run(people_2(),
										table_name="people_1",
										write_disposition="merge",
                               primary_key="ID")
# show outcome

import duckdb

conn = duckdb.connect(f"{generators_pipeline.pipeline_name}.duckdb")

# let's see the tables
conn.sql(f"SET search_path = '{generators_pipeline.dataset_name}'")
print('Loaded tables: ')
display(conn.sql("show tables"))

# and the data

print("\n\n\n http_download table below:")

people = conn.sql("SELECT * FROM people_1").df()
age_sum=conn.sql("SELECT SUM(age) FROM people_1")
display(people,age_sum)

2024-02-13 22:34:53,419|[WARNING              ]|266|133297725386752|dlt|reference.py|_verify_schema:357|A column record_hash in table people_1 in schema dlt_colab_kernel_launcher is incomplete. It was not bound to the data during normalizations stage and its data type is unknown. Did you add this column manually in code ie. as a merge key?
2024-02-13 22:34:54,032|[WARNING              ]|266|133297725386752|dlt|reference.py|_verify_schema:357|A column record_hash in table people_1 in schema dlt_colab_kernel_launcher is incomplete. It was not bound to the data during normalizations stage and its data type is unknown. Did you add this column manually in code ie. as a merge key?
2024-02-13 22:34:54,040|[WARNING              ]|266|133297725386752|dlt|reference.py|_verify_schema:357|A column record_hash in table people_1 in schema dlt_colab_kernel_launcher is incomplete. It was not bound to the data during normalizations stage and its data type is unknown. Did you add this column manually in code ie. as a merge key?

Loaded tables:

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people_1            │
└─────────────────────┘

 http_download table below:

   id      name  age    city        _dlt_load_id         _dlt_id occupation
0   1  Person_1   26  City_A  1707863693.0301912  wIIN9n3Cuc1Xhg       None
1   2  Person_2   27  City_A  1707863693.0301912  RPLClyTnJBa/mQ       None
2   5  Person_5   35  City_B  1707863693.6383781  npk6rAeQF0+JTA      Job_5
3   7  Person_7   37  City_B  1707863693.6383781  xDJA1jQitds9hw      Job_7
4   4  Person_4   34  City_B  1707863693.6383781  /6tiwUGlxQziDA      Job_4
5   3  Person_3   33  City_B  1707863693.6383781  Zl3B+0FrQzkWYw      Job_3
6   6  Person_6   36  City_B  1707863693.6383781  zAbjUxVoIv7tRA      Job_6
7   8  Person_8   38  City_B  1707863693.6383781  eM+pN+jgYuv3GQ      Job_8

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      266 │
└──────────┘

# 3. Merge a generator

Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

Question: **Calculate the sum of ages of all the people loaded as described above.**

# Solution: First make sure that the following modules are installed:

In [3]:
#Install the dependencies
%%capture
!pip install dlt[duckdb]

In [32]:
# to do: homework :)

Questions? difficulties? We are here to help.
- DTC data engineering course channel: https://datatalks-club.slack.com/archives/C01FABYF2RG
- dlt's DTC cohort channel: https://dlthub-community.slack.com/archives/C06GAEX2VNX